'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Check, PackageCheck, Plus, RotateCcw, Search, Trash2 } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { confirmRemoval } from '@/lib/client-ui';

export default function InventoryManager({ camporeeId, canEdit, initialItems }: { camporeeId:string; canEdit:boolean; initialItems:any[] }) {
  const [items,setItems]=useState(initialItems); const [open,setOpen]=useState(false); const [query,setQuery]=useState(''); const supabase=createClient(); const router=useRouter();
  useEffect(()=>setItems(initialItems),[initialItems]);
  const visible=useMemo(()=>items.filter(i=>`${i.name} ${i.notes??''}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  async function addItem(formData:FormData){if(!canEdit)return;const name=String(formData.get('name')||'').trim();if(!name)return;const payload={camporee_id:camporeeId,name,quantity:Number(formData.get('quantity')||1),unit:String(formData.get('unit')||'').trim()||null,notes:String(formData.get('notes')||'').trim()||null};const{data,error}=await supabase.from('inventory_items').insert(payload).select('*').single();if(!error&&data){setItems(c=>[data,...c]);setOpen(false);router.refresh()}}
  async function toggle(id:string,field:'packed'|'returned',value:boolean){if(!canEdit)return;setItems(c=>c.map(i=>i.id===id?{...i,[field]:value}:i));const{error}=await supabase.from('inventory_items').update({[field]:value}).eq('id',id);if(error){router.refresh();return}router.refresh()}
  async function remove(id:string){if(!canEdit||!confirmRemoval('este elemento'))return;const previous=items;setItems(c=>c.filter(i=>i.id!==id));const{error}=await supabase.from('inventory_items').delete().eq('id',id);if(error)setItems(previous);else router.refresh()}
  const packed=items.filter(i=>i.packed).length, returned=items.filter(i=>i.returned).length;
  return <><section className='inventory-summary'><div className='ios-card mini-stat'><strong>{packed}/{items.length}</strong><small>Empacados</small></div><div className='ios-card mini-stat'><strong>{returned}/{items.length}</strong><small>Regresaron</small></div></section><div className='panel-tools'><label className='panel-search'><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='Buscar equipo o material'/></label>{canEdit?<button className='panel-add' onClick={()=>setOpen(true)}><Plus size={18}/> Agregar al inventario</button>:null}</div>{open?<div className='sheet-backdrop' onClick={()=>setOpen(false)}><section className='sheet-card' role='dialog' aria-modal='true' onClick={e=>e.stopPropagation()}><div className='sheet-handle'/><h2>Nuevo elemento</h2><form action={addItem} className='panel-form'><input name='name' placeholder='Carpa, olla, extensión…' required/><div className='form-two'><input name='quantity' type='number' min='0' step='0.01' defaultValue='1'/><input name='unit' placeholder='Unidad'/></div><textarea name='notes' placeholder='Notas'/><button className='primary-btn'>Guardar</button></form></section></div>:null}<section className='panel-list'>{visible.length?visible.map(item=><article className='panel-row ios-card' key={item.id}><span className='stat-icon stat-blue'><PackageCheck size={18}/></span><div className='panel-row-copy'><strong>{item.name}</strong><small>{item.quantity} {item.unit??''}</small>{item.notes?<small>{item.notes}</small>:null}</div><div className='inventory-actions'><button className={`status-btn ${item.packed?'selected':''}`} onClick={()=>toggle(item.id,'packed',!item.packed)} disabled={!canEdit} aria-label='Empacado'><Check size={16}/></button><button className={`status-btn ${item.returned?'selected':''}`} onClick={()=>toggle(item.id,'returned',!item.returned)} disabled={!canEdit} aria-label='Regresó'><RotateCcw size={16}/></button>{canEdit?<button className='row-icon-btn danger' onClick={()=>remove(item.id)}><Trash2 size={16}/></button>:null}</div></article>):<div className='empty compact'>No hay elementos en el inventario todavía.</div>}</section></>
}
