'use client';

import BottomSheet from '@/app/components/bottom-sheet';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Check, Package, Plus, RotateCcw, Search, Trash2 } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { confirmRemoval, reportMutationError, reportMutationSuccess } from '@/lib/client-ui';

export default function InventoryManager({ camporeeId, canEdit, initialItems }: { camporeeId:string; canEdit:boolean; initialItems:any[] }) {
  const [statusFilter,setStatusFilter]=useState<'all'|'unpacked'|'returned'>('all'); const [items,setItems]=useState(initialItems); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [formError,setFormError]=useState(''); const [query,setQuery]=useState(''); const supabase=createClient(); const router=useRouter();
  useEffect(()=>setItems(initialItems),[initialItems]);
  const visible=useMemo(()=>items.filter(i=>`${i.name} ${i.notes??''}`.toLowerCase().includes(query.toLowerCase()) && (statusFilter==='all'||statusFilter==='unpacked'&&!i.packed||statusFilter==='returned'&&i.packed&&!i.returned)),[items,query,statusFilter]);
  async function addItem(formData:FormData){if(!canEdit||saving)return;const name=String(formData.get('name')||'').trim();if(!name){setFormError('Escribe el nombre del elemento.');return;}setSaving(true);setFormError('');try{const payload={camporee_id:camporeeId,name,quantity:Number(formData.get('quantity')||1),unit:String(formData.get('unit')||'').trim()||null,notes:String(formData.get('notes')||'').trim()||null};const{data,error}=await supabase.from('inventory_items').insert(payload).select('*').single();if(error||!data){const message=reportMutationError(error,'No se pudo guardar el elemento del inventario.');setFormError(message);return;}setItems(c=>[data,...c]);setOpen(false);reportMutationSuccess('Elemento guardado.');router.refresh()}catch(error){const message=reportMutationError(error,'No se pudo guardar el elemento del inventario.');setFormError(message)}finally{setSaving(false)}}
  async function toggle(id:string,field:'packed'|'returned',value:boolean){if(!canEdit)return;const previous=items;setItems(c=>c.map(i=>i.id===id?{...i,[field]:value}:i));const{error}=await supabase.from('inventory_items').update({[field]:value}).eq('id',id);if(error){setItems(previous);reportMutationError(error,'No se pudo actualizar el inventario.');return}router.refresh()}
  async function remove(id:string){if(!canEdit||!confirmRemoval('este elemento'))return;const previous=items;setItems(c=>c.filter(i=>i.id!==id));const{error}=await supabase.from('inventory_items').delete().eq('id',id);if(error){setItems(previous);reportMutationError(error,'No se pudo eliminar el elemento.')}else{reportMutationSuccess('Elemento eliminado.');router.refresh()}}
  const packed=items.filter(i=>i.packed).length, returned=items.filter(i=>i.returned).length;
  return <>
    <section className="pm-inventory-stats"><div><small>Empacado</small><strong>{packed}/{items.length}</strong></div><div><small>Regresó</small><strong>{returned}/{items.length}</strong></div></section>
    <label className="pm-search"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar artículo"/><span><Search size={18}/></span></label>
    <div className="pm-segment"><button type="button" className={statusFilter==='all'?'active':''} onClick={()=>setStatusFilter('all')}>Todo</button><button type="button" className={statusFilter==='unpacked'?'active':''} onClick={()=>setStatusFilter('unpacked')}>Por empacar</button><button type="button" className={statusFilter==='returned'?'active':''} onClick={()=>setStatusFilter('returned')}>Regreso</button></div>
    <BottomSheet open={Boolean(open)} onClose={()=>{if(!saving)setOpen(false)}} title={<>Nuevo artículo</>} busy={saving}><form onSubmit={event=>{event.preventDefault();void addItem(new FormData(event.currentTarget))}} className="panel-form pm-sheet-form"><div className="pm-sheet-fields">{formError?<div className="auth-alert error" role="alert">{formError}</div>:null}<label className="pm-field"><span>Artículo <b className="pm-required">*</b></span><input name="name"  required/></label><div className="form-two"><label className="pm-field"><span>Cantidad</span><input name="quantity" type="number" min="0" step="0.01" defaultValue="1"/></label><label className="pm-field"><span>Unidad</span><input name="unit" /></label></div><label className="pm-field"><span>Notas</span><textarea name="notes" /></label></div><div className="pm-sheet-footer"><button type="submit" className="primary-btn" disabled={saving}>{saving ? 'Guardando…' : 'Guardar'}</button></div></form></BottomSheet>
    <section className="pm-inventory-list">{visible.length?visible.map(item=><article className="pm-inventory-row" key={item.id}><span className={'pm-icon '+(item.packed?'pm-packed':'')}><Package size={20}/></span><div className="pm-inventory-copy"><strong>{item.name}</strong><small>{item.quantity} {item.unit||'ud'}{item.notes?` · ${item.notes}`:''}</small>{item.returned?<small className="pm-returned">Regresó</small>:null}</div><button type="button" className={'pm-pack-btn '+(item.packed?'packed':'')} onClick={()=>toggle(item.id,'packed',!item.packed)} disabled={!canEdit}>{item.packed?'Empacado':'Empacar'}</button><div className="pm-row-more">{canEdit?<><button type="button" onClick={()=>toggle(item.id,'returned',!item.returned)} aria-label={item.returned?'Desmarcar regreso':'Marcar regreso'} title="Marcar regreso"><RotateCcw size={16}/></button><button type="button" onClick={()=>remove(item.id)} aria-label="Eliminar artículo"><Trash2 size={16}/></button></>:null}</div></article>):<div className="empty compact">No hay artículos que coincidan con este filtro.</div>}</section>
    {canEdit?<button type="button" className="pm-fab" onClick={()=>{setFormError('');setOpen(true)}}><Plus size={20}/> Artículo</button>:null}
  </>;
}
